
# values to be used for all test cases
[global]
savedir = "/tmp/lwfm/wf01"
P_in = 200
P_out = 0
U_top = 0
U_bottom = 0
L = 1
D = 1
mu = 1
rho = 1
var = "pressure"


# *****************************************************************************
# test cases

[test01]
NQ_MATRIX = 2
nx = 2
ny = 3
case = "sample-tridiag"

[test02]
NQ_MATRIX = 2
nx = 2
ny = 3
case = "hele-shaw"

[test03]
NQ_MATRIX = 3
nx = 2
ny = 3
case = "hele-shaw"

