
# values to be used for all test cases
[global]
savedir = "/tmp/lwfm/qt02-cfd/wf01"
circuit_hhl_path = "~/proj/src/frontier-qlsa/frontier_qlsa/circuit_HHL.py"
qc_backend = "statevector_sim_aer"
preprocess_site = "frontier-qlsa"
exec_site = "ibm-quantum"

# ORNL CFD variables
P_in = 200          # inlet pressure
P_out = 0           # outlet pressure
U_top = 0           # top velocity
U_bottom = 0        # bottom velocity
L = 1               # length
D = 1               # depth
mu = 1              # dynamic viscosity
rho = 1             # fluid density
case = "sample-tridiag"
NQ_MATRIX = 2
nx = 2
ny = 2
var = "pressure"

# *****************************************************************************
# test cases

[case-100]
qc_shots = 100

[case-1000]
qc_shots = 1000

[case-10000]
qc_shots = 10000

[case-100000]
qc_shots = 100000

[case-1000000]
qc_shots = 1000000


